/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProjectsRouteRouteImport } from './routes/_dashboard/projects/route'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardProjectsProfileRouteImport } from './routes/_dashboard/projects/profile'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard/projects/$projectId/index'
import { Route as DashboardProjectsProjectIdControllersControllerIdIndexRouteImport } from './routes/_dashboard/projects/$projectId/controllers/$controllerId/index'
import { Route as DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRouteImport } from './routes/_dashboard/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsRouteRoute = DashboardProjectsRouteRouteImport.update({
  id: '/_dashboard/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRouteRoute,
} as any)
const DashboardProjectsProfileRoute =
  DashboardProjectsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardProjectsRouteRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => DashboardProjectsRouteRoute,
  } as any)
const DashboardProjectsProjectIdControllersControllerIdIndexRoute =
  DashboardProjectsProjectIdControllersControllerIdIndexRouteImport.update({
    id: '/$projectId/controllers/$controllerId/',
    path: '/$projectId/controllers/$controllerId/',
    getParentRoute: () => DashboardProjectsRouteRoute,
  } as any)
const DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute =
  DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRouteImport.update(
    {
      id: '/$projectId/controllers/$controllerId/endpoints/$endpointId',
      path: '/$projectId/controllers/$controllerId/endpoints/$endpointId',
      getParentRoute: () => DashboardProjectsRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof DashboardProjectsRouteRouteWithChildren
  '/projects/profile': typeof DashboardProjectsProfileRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/controllers/$controllerId/': typeof DashboardProjectsProjectIdControllersControllerIdIndexRoute
  '/projects/$projectId/controllers/$controllerId/endpoints/$endpointId': typeof DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/profile': typeof DashboardProjectsProfileRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/controllers/$controllerId': typeof DashboardProjectsProjectIdControllersControllerIdIndexRoute
  '/projects/$projectId/controllers/$controllerId/endpoints/$endpointId': typeof DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteRouteWithChildren
  '/_dashboard/projects/profile': typeof DashboardProjectsProfileRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/projects/$projectId/controllers/$controllerId/': typeof DashboardProjectsProjectIdControllersControllerIdIndexRoute
  '/_dashboard/projects/$projectId/controllers/$controllerId/endpoints/$endpointId': typeof DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/profile'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/controllers/$controllerId/'
    | '/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/profile'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/controllers/$controllerId'
    | '/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard/projects'
    | '/_dashboard/projects/profile'
    | '/_dashboard/projects/'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/projects/$projectId/controllers/$controllerId/'
    | '/_dashboard/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardProjectsRouteRoute: typeof DashboardProjectsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRouteRoute
    }
    '/_dashboard/projects/profile': {
      id: '/_dashboard/projects/profile'
      path: '/profile'
      fullPath: '/projects/profile'
      preLoaderRoute: typeof DashboardProjectsProfileRouteImport
      parentRoute: typeof DashboardProjectsRouteRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsRouteRoute
    }
    '/_dashboard/projects/$projectId/controllers/$controllerId/': {
      id: '/_dashboard/projects/$projectId/controllers/$controllerId/'
      path: '/$projectId/controllers/$controllerId'
      fullPath: '/projects/$projectId/controllers/$controllerId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdControllersControllerIdIndexRouteImport
      parentRoute: typeof DashboardProjectsRouteRoute
    }
    '/_dashboard/projects/$projectId/controllers/$controllerId/endpoints/$endpointId': {
      id: '/_dashboard/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'
      path: '/$projectId/controllers/$controllerId/endpoints/$endpointId'
      fullPath: '/projects/$projectId/controllers/$controllerId/endpoints/$endpointId'
      preLoaderRoute: typeof DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRouteImport
      parentRoute: typeof DashboardProjectsRouteRoute
    }
  }
}

interface DashboardProjectsRouteRouteChildren {
  DashboardProjectsProfileRoute: typeof DashboardProjectsProfileRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
  DashboardProjectsProjectIdControllersControllerIdIndexRoute: typeof DashboardProjectsProjectIdControllersControllerIdIndexRoute
  DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute: typeof DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute
}

const DashboardProjectsRouteRouteChildren: DashboardProjectsRouteRouteChildren =
  {
    DashboardProjectsProfileRoute: DashboardProjectsProfileRoute,
    DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
    DashboardProjectsProjectIdControllersControllerIdIndexRoute:
      DashboardProjectsProjectIdControllersControllerIdIndexRoute,
    DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute:
      DashboardProjectsProjectIdControllersControllerIdEndpointsEndpointIdRoute,
  }

const DashboardProjectsRouteRouteWithChildren =
  DashboardProjectsRouteRoute._addFileChildren(
    DashboardProjectsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardProjectsRouteRoute: DashboardProjectsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
